package no.uib.prideconverter.gui;

import no.uib.prideconverter.PRIDEConverter;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import no.uib.prideconverter.filefilters.DtaFileFilter;
import no.uib.prideconverter.filefilters.OutFileFilter;
import no.uib.prideconverter.filefilters.PklFileFilter;
import no.uib.prideconverter.filefilters.PklSpoFileFilter;

/**
 * This frame handles the selection of the data files to be converted for 
 * dataformats with two files, e.g., Spectrum Mill or Sequest.
 * 
 * @author Harald Barsnes
 * 
 * Created March 2008
 */
public class DataFileSelectionTwoFileTypes extends javax.swing.JFrame {

    private PRIDEConverter prideConverter;

    /** 
     * Opens a new DataFileSelectionTwoFileTypes frame, and inserts stored information.
     * 
     * @param prideConverter
     * @param location where to position the frame
     */
    public DataFileSelectionTwoFileTypes(PRIDEConverter prideConverter, Point location) {

        this.prideConverter = prideConverter;

        // sets the default wizard frame size
        this.setPreferredSize(new Dimension(prideConverter.getProperties().FRAME_WIDTH,
                prideConverter.getProperties().FRAME_HEIGHT));
        this.setSize(prideConverter.getProperties().FRAME_WIDTH,
                prideConverter.getProperties().FRAME_HEIGHT);
        this.setMaximumSize(new Dimension(prideConverter.getProperties().FRAME_WIDTH,
                prideConverter.getProperties().FRAME_HEIGHT));
        this.setMinimumSize(new Dimension(prideConverter.getProperties().FRAME_WIDTH,
                prideConverter.getProperties().FRAME_HEIGHT));

        initComponents();

        selectedSpectraFilesJTable.getTableHeader().setReorderingAllowed(false);
        selectedIdentificationFilesJTable.getTableHeader().setReorderingAllowed(false);

        selectedSpectraFilesJTable.getColumn(" ").setMinWidth(40);
        selectedSpectraFilesJTable.getColumn(" ").setMaxWidth(40);
        selectedIdentificationFilesJTable.getColumn(" ").setMinWidth(40);
        selectedIdentificationFilesJTable.getColumn(" ").setMaxWidth(40);

        // insert stored information
        if (prideConverter.getProperties().getSelectedSourceFiles() != null) {

            for (int i = 0; i < prideConverter.getProperties().getSelectedSourceFiles().size(); i++) {

                ((DefaultTableModel) selectedSpectraFilesJTable.getModel()).addRow(
                        new Object[]{
                    new Integer(selectedSpectraFilesJTable.getRowCount() + 1),
                    new File(prideConverter.getProperties().getSelectedSourceFiles().get(i)).getName()
                });
            }
        } else {
            prideConverter.getProperties().setSelectedSourceFiles(new ArrayList());
        }

        if (prideConverter.getProperties().getSelectedIdentificationFiles() != null) {

            for (int i = 0; i < prideConverter.getProperties().getSelectedIdentificationFiles().size(); i++) {
                ((DefaultTableModel) selectedIdentificationFilesJTable.getModel()).addRow(
                        new Object[]{
                    new Integer(selectedIdentificationFilesJTable.getRowCount() +
                    1),
                    new File(prideConverter.getProperties().getSelectedIdentificationFiles().get(i)).getName()
                });
            }

            if (selectedIdentificationFilesJTable.getRowCount() > 0 &&
                    selectedSpectraFilesJTable.getRowCount() > 0) {
                nextJButton.setEnabled(true);
            }
        } else {
            prideConverter.getProperties().setSelectedIdentificationFiles(new ArrayList());
        }

        // sets the icon of the frame
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().
                getResource("/no/uib/prideconverter/icons/prideConverter_16.GIF")));

        setTitle(prideConverter.getWizardName() + " " + prideConverter.getPrideConverterVersionNumber() +
                " - " + getTitle());

        if (location != null) {
            setLocation(location);
        } else {
            setLocationRelativeTo(null);
        }

        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        deleteSelectedSpectraFilesJPopupMenu = new javax.swing.JPopupMenu();
        deleteSpectraJMenuItem = new javax.swing.JMenuItem();
        deleteSelectedIdentificationFilesJPopupMenu = new javax.swing.JPopupMenu();
        deleteIdentificationsJMenuItem = new javax.swing.JMenuItem();
        nextJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        cancelJButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        selectedSpectraFilesJTable = new javax.swing.JTable();
        selectSpectrumFileOrFolderJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        helpJButton = new javax.swing.JButton();
        aboutJButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        selectedIdentificationFilesJTable = new javax.swing.JTable();
        selectIdentificationsFileOrFolderJButton = new javax.swing.JButton();

        deleteSpectraJMenuItem.setText("Delete Selected Row(s)");
        deleteSpectraJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSpectraJMenuItemActionPerformed(evt);
            }
        });
        deleteSelectedSpectraFilesJPopupMenu.add(deleteSpectraJMenuItem);

        deleteIdentificationsJMenuItem.setText("Delete Selected Row(s)");
        deleteIdentificationsJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteIdentificationsJMenuItemActionPerformed(evt);
            }
        });
        deleteSelectedIdentificationFilesJPopupMenu.add(deleteIdentificationsJMenuItem);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("File Selection - Step 1 of 8");
        setMinimumSize(new java.awt.Dimension(580, 560));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        nextJButton.setText("Next  >");
        nextJButton.setEnabled(false);
        nextJButton.setPreferredSize(new java.awt.Dimension(81, 23));
        nextJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextJButtonActionPerformed(evt);
            }
        });

        backJButton.setText("< Back");
        backJButton.setPreferredSize(new java.awt.Dimension(81, 23));
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        cancelJButton.setText("Cancel");
        cancelJButton.setPreferredSize(new java.awt.Dimension(81, 23));
        cancelJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelJButtonActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Spectrum Files", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Selected Files:");

        selectedSpectraFilesJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " ", "File"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        selectedSpectraFilesJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectedSpectraFilesJTableMouseClicked(evt);
            }
        });
        selectedSpectraFilesJTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                selectedSpectraFilesJTableKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(selectedSpectraFilesJTable);

        selectSpectrumFileOrFolderJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/no/uib/prideconverter/icons/Directory.gif"))); // NOI18N
        selectSpectrumFileOrFolderJButton.setText("Select a File or a Folder");
        selectSpectrumFileOrFolderJButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        selectSpectrumFileOrFolderJButton.setMaximumSize(new java.awt.Dimension(167, 23));
        selectSpectrumFileOrFolderJButton.setMinimumSize(new java.awt.Dimension(167, 23));
        selectSpectrumFileOrFolderJButton.setPreferredSize(new java.awt.Dimension(167, 23));
        selectSpectrumFileOrFolderJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectSpectrumFileOrFolderJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(selectSpectrumFileOrFolderJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectSpectrumFileOrFolderJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel3.setText("Select the files you want to convert data from, and click on 'Next'  to continue.");

        helpJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/no/uib/prideconverter/icons/help.GIF"))); // NOI18N
        helpJButton.setToolTipText("Help");
        helpJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpJButtonActionPerformed(evt);
            }
        });

        aboutJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/no/uib/prideconverter/icons/prideConverter_16.GIF"))); // NOI18N
        aboutJButton.setToolTipText("About");
        aboutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutJButtonActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Identification Files", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0)));

        jLabel5.setText("Selected Files:");

        selectedIdentificationFilesJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " ", "File"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        selectedIdentificationFilesJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectedIdentificationFilesJTableMouseClicked(evt);
            }
        });
        selectedIdentificationFilesJTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                selectedIdentificationFilesJTableKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(selectedIdentificationFilesJTable);

        selectIdentificationsFileOrFolderJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/no/uib/prideconverter/icons/Directory.gif"))); // NOI18N
        selectIdentificationsFileOrFolderJButton.setText("Select a File or a Folder");
        selectIdentificationsFileOrFolderJButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        selectIdentificationsFileOrFolderJButton.setMaximumSize(new java.awt.Dimension(167, 23));
        selectIdentificationsFileOrFolderJButton.setMinimumSize(new java.awt.Dimension(167, 23));
        selectIdentificationsFileOrFolderJButton.setPreferredSize(new java.awt.Dimension(167, 23));
        selectIdentificationsFileOrFolderJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectIdentificationsFileOrFolderJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(selectIdentificationsFileOrFolderJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectIdentificationsFileOrFolderJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(helpJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aboutJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                        .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nextJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(helpJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aboutJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Closes the frame and the wizard.
     * 
     * @param evt
     */
    private void cancelJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelJButtonActionPerformed
        this.setVisible(false);
        this.dispose();
        prideConverter.cancelConvertion();
    }//GEN-LAST:event_cancelJButtonActionPerformed

    /**
     * Tries to connect to the database and go to the next step (ProjectSelection).
     * 
     * @param evt
     */
    private void nextJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextJButtonActionPerformed

        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        new SpectraSelectionWithIdentifications(prideConverter, this.getLocation());
        this.setVisible(false);
        this.dispose();

        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_nextJButtonActionPerformed

    /**
     * See cancelJButtonActionPerformed
     * 
     * @param evt
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cancelJButtonActionPerformed(null);
    }//GEN-LAST:event_formWindowClosing

    /**
     * Opens a Help window.
     * 
     * @param evt
     */
    private void helpJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpJButtonActionPerformed
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        new HelpWindow(this, getClass().getResource("/no/uib/prideconverter/helpfiles/DataFileSelection_TwoFileTypes.html"));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
}//GEN-LAST:event_helpJButtonActionPerformed

    /**
     * Opens an About PRIDE Converter window.
     * 
     * @param evt
     */
    private void aboutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutJButtonActionPerformed
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        new HelpWindow(this, getClass().getResource("/no/uib/prideconverter/helpfiles/AboutPRIDE_Converter.html"));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_aboutJButtonActionPerformed

    /**
     * Closes the frame and opens the previous frame (DataSourceSelection).
     * 
     * @param evt
     */
    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        new DataSourceSelection(prideConverter, this.getLocation());
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_backJButtonActionPerformed

    /**
     * Deletes the selected spectra files in the table.
     * 
     * @param evt
     */
    private void deleteSpectraJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSpectraJMenuItemActionPerformed
        if (selectedSpectraFilesJTable.getSelectedRow() != -1) {

            prideConverter.getProperties().setSpectrumTableModel(null);

            int[] selectedRows = selectedSpectraFilesJTable.getSelectedRows();

            for (int i = selectedRows.length - 1; i >= 0; i--) {
                prideConverter.getProperties().getSelectedSourceFiles().remove(selectedRows[i]);
                ((DefaultTableModel) selectedSpectraFilesJTable.getModel()).removeRow(selectedRows[i]);
            }

            fixSpectraTableIndices();

            nextJButton.setEnabled(selectedSpectraFilesJTable.getRowCount() > 0);
        }
}//GEN-LAST:event_deleteSpectraJMenuItemActionPerformed

    /**
     * If the user right clicks in the spectra files table a popup menu is 
     * shown.
     * 
     * @param evt
     */
    private void selectedSpectraFilesJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectedSpectraFilesJTableMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON3) {

            int row = selectedSpectraFilesJTable.rowAtPoint(evt.getPoint());
            int column = selectedSpectraFilesJTable.columnAtPoint(evt.getPoint());

            int[] selectedRows = selectedSpectraFilesJTable.getSelectedRows();

            if (selectedRows.length > 0) {
                if (row < selectedRows[0] || row >
                        selectedRows[selectedRows.length - 1]) {
                    selectedSpectraFilesJTable.changeSelection(row, column, false, false);
                }
            } else {
                selectedSpectraFilesJTable.changeSelection(row, column, false, false);
            }

            deleteSelectedSpectraFilesJPopupMenu.show(evt.getComponent(), evt.getX(), evt.getY());
        }
}//GEN-LAST:event_selectedSpectraFilesJTableMouseClicked

    /**
     * Opens a file chooser where the user can select the files add to the 
     * table.
     * 
     * @param evt
     */
    private void selectSpectrumFileOrFolderJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectSpectrumFileOrFolderJButtonActionPerformed
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));

        JFileChooser chooser = new JFileChooser(prideConverter.getUserProperties().getCurrentSourceFileLocation());
        chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        chooser.setMultiSelectionEnabled(true);
        if (prideConverter.getProperties().getDataSource().equalsIgnoreCase("Spectrum Mill")) {
            chooser.setFileFilter(new PklFileFilter());
        } else if (prideConverter.getProperties().getDataSource().equalsIgnoreCase("Sequest Result File")) {
            chooser.setFileFilter(new DtaFileFilter());
        }

        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String path;

            prideConverter.getProperties().setSpectrumTableModel(null);
            prideConverter.getProperties().setInstrumentDetailsExtracted(false);
            prideConverter.getProperties().setSelectedSourceFiles(new ArrayList());
            prideConverter.getProperties().setSpectraSelectionCriteria(null);
            prideConverter.getProperties().setDataFileHasBeenLoaded(false);
            prideConverter.getProperties().setSampleDetailsExtracted(false);
            prideConverter.getProperties().setContactInfoExtracted(false);
            prideConverter.getProperties().setCurrentQuantificationSelection(new ArrayList());

            while (selectedSpectraFilesJTable.getRowCount() > 0) {
                ((DefaultTableModel) selectedSpectraFilesJTable.getModel()).removeRow(0);
            }

            prideConverter.getUserProperties().setSourceFileLocation(chooser.getSelectedFile().getPath());

            File[] allFiles = chooser.getSelectedFiles();

            for (int j = 0; j < allFiles.length; j++) {

                File currentFile = allFiles[j];

                if (currentFile.isDirectory()) {

                    File[] files = chooser.getSelectedFile().listFiles();
                    File tempFile;

                    for (int i = 0; i < files.length; i++) {
                        tempFile = files[i];

                        if (prideConverter.getProperties().getDataSource().equalsIgnoreCase("Spectrum Mill")) {
                            if (tempFile.getAbsolutePath().endsWith(".pkl") ||
                                    tempFile.getAbsolutePath().endsWith(".PKL")) {
                                if (!prideConverter.getProperties().getSelectedSourceFiles().contains(
                                        tempFile)) {
                                    ((DefaultTableModel) selectedSpectraFilesJTable.getModel()).addRow(
                                            new Object[]{
                                        new Integer(selectedSpectraFilesJTable.getRowCount() + 1),
                                        tempFile.getName(),
                                        new Boolean(true)
                                    });

                                    prideConverter.getProperties().getSelectedSourceFiles().add(tempFile.getPath());
                                } else {
                                    JOptionPane.showMessageDialog(this, "A file with the name " +
                                            tempFile.getPath() +
                                            " is already selected.\nThe same file can not be added twice.", "File Already Selected", JOptionPane.ERROR_MESSAGE);
                                }
                            }
                        } else {
                            if (prideConverter.getProperties().getDataSource().equalsIgnoreCase("Sequest Result File")) {
                                if (tempFile.getAbsolutePath().endsWith(".dta") ||
                                        tempFile.getAbsolutePath().endsWith(".DTA")) {
                                    if (!prideConverter.getProperties().getSelectedSourceFiles().contains(
                                            tempFile)) {
                                        ((DefaultTableModel) selectedSpectraFilesJTable.getModel()).addRow(
                                                new Object[]{
                                            new Integer(selectedSpectraFilesJTable.getRowCount() + 1),
                                            tempFile.getName(),
                                            new Boolean(true)
                                        });

                                        prideConverter.getProperties().getSelectedSourceFiles().add(tempFile.getPath());
                                    } else {
                                        JOptionPane.showMessageDialog(this, "A file with the name " +
                                                tempFile.getPath() +
                                                " is already selected.\nThe same file can not be added twice.", "File Already Selected", JOptionPane.ERROR_MESSAGE);
                                    }
                                }
                            }
                        }
                    }
                } else {
                    if (!prideConverter.getProperties().getSelectedSourceFiles().contains(
                            currentFile.getPath())) {
                        ((DefaultTableModel) selectedSpectraFilesJTable.getModel()).addRow(
                                new Object[]{
                            new Integer(selectedSpectraFilesJTable.getRowCount() +
                            1),
                            currentFile.getName(),
                            new Boolean(true)
                        });

                        prideConverter.getProperties().getSelectedSourceFiles().add(currentFile.getPath());
                    } else {
                        JOptionPane.showMessageDialog(this, "A file with the name " +
                                currentFile.getPath() +
                                " is already selected.\nThe same file can not be added twice.", "File Already Selected", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }

        if (selectedIdentificationFilesJTable.getRowCount() > 0 &&
                selectedSpectraFilesJTable.getRowCount() > 0) {
            nextJButton.setEnabled(true);
        }

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
}//GEN-LAST:event_selectSpectrumFileOrFolderJButtonActionPerformed

    /**
     * If the user right clicks in the identification files table a popup menu 
     * is shown.
     * 
     * @param evt
     */
    private void selectedIdentificationFilesJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectedIdentificationFilesJTableMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON3) {

            int row = selectedIdentificationFilesJTable.rowAtPoint(evt.getPoint());
            int column = selectedIdentificationFilesJTable.columnAtPoint(evt.getPoint());

            int[] selectedRows = selectedIdentificationFilesJTable.getSelectedRows();

            if (selectedRows.length > 0) {
                if (row < selectedRows[0] || row >
                        selectedRows[selectedRows.length - 1]) {
                    selectedIdentificationFilesJTable.changeSelection(row, column, false, false);
                }
            } else {
                selectedIdentificationFilesJTable.changeSelection(row, column, false, false);
            }

            deleteSelectedIdentificationFilesJPopupMenu.show(evt.getComponent(), evt.getX(), evt.getY());
        }
}//GEN-LAST:event_selectedIdentificationFilesJTableMouseClicked

    /**
     * Opens a file chooser where the files to be added to the identification 
     * files folder can be selected.
     * 
     * @param evt
     */
    private void selectIdentificationsFileOrFolderJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectIdentificationsFileOrFolderJButtonActionPerformed
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));

        JFileChooser chooser = new JFileChooser(prideConverter.getUserProperties().getCurrentSourceFileLocation());
        chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        chooser.setMultiSelectionEnabled(true);
        if (prideConverter.getProperties().getDataSource().equalsIgnoreCase("Spectrum Mill")) {
            chooser.setFileFilter(new PklSpoFileFilter());
        } else if (prideConverter.getProperties().getDataSource().equalsIgnoreCase("Sequest Result File")) {
            chooser.setFileFilter(new OutFileFilter());
        }

        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String path;

            prideConverter.getProperties().setSpectrumTableModel(null);
            prideConverter.getProperties().setSelectedIdentificationFiles(new ArrayList());
            prideConverter.getProperties().setSpectraSelectionCriteria(null);

            while (selectedIdentificationFilesJTable.getRowCount() > 0) {
                ((DefaultTableModel) selectedIdentificationFilesJTable.getModel()).removeRow(0);
            }

            prideConverter.getUserProperties().setSourceFileLocation(chooser.getSelectedFile().getPath());

            File[] allFiles = chooser.getSelectedFiles();

            for (int j = 0; j < allFiles.length; j++) {

                File currentFile = allFiles[j];

                if (currentFile.isDirectory()) {

                    File[] files = currentFile.listFiles();
                    File tempFile;

                    for (int i = 0; i < files.length; i++) {
                        tempFile = files[i];

                        if (prideConverter.getProperties().getDataSource().equalsIgnoreCase("Spectrum Mill")) {
                            if (tempFile.getAbsolutePath().endsWith(".spo") ||
                                    tempFile.getAbsolutePath().endsWith(".SPO")) {
                                if (!prideConverter.getProperties().getSelectedIdentificationFiles().contains(
                                        tempFile)) {
                                    ((DefaultTableModel) selectedIdentificationFilesJTable.getModel()).addRow(
                                            new Object[]{
                                        new Integer(selectedIdentificationFilesJTable.getRowCount() + 1),
                                        tempFile.getName(),
                                        new Boolean(true)
                                    });

                                    prideConverter.getProperties().getSelectedIdentificationFiles().add(tempFile.getPath());
                                } else {
                                    JOptionPane.showMessageDialog(this,
                                            "A file with the name " + tempFile.getPath() +
                                            " is already selected.\nThe same file can not be added twice.",
                                            "File Already Selected", JOptionPane.ERROR_MESSAGE);
                                }
                            }
                        } else if (prideConverter.getProperties().getDataSource().equalsIgnoreCase("Sequest Result File")) {
                            if (tempFile.getAbsolutePath().endsWith(".out") ||
                                    tempFile.getAbsolutePath().endsWith(".OUT")) {
                                if (!prideConverter.getProperties().getSelectedIdentificationFiles().contains(
                                        tempFile)) {
                                    ((DefaultTableModel) selectedIdentificationFilesJTable.getModel()).addRow(
                                            new Object[]{
                                        new Integer(selectedIdentificationFilesJTable.getRowCount() + 1),
                                        tempFile.getName(),
                                        new Boolean(true)
                                    });

                                    prideConverter.getProperties().getSelectedIdentificationFiles().add(tempFile.getPath());
                                } else {
                                    JOptionPane.showMessageDialog(this,
                                            "A file with the name " + tempFile.getPath() +
                                            " is already selected.\nThe same file can not be added twice.",
                                            "File Already Selected", JOptionPane.ERROR_MESSAGE);
                                }
                            }
                        }
                    }
                } else {

                    if (!prideConverter.getProperties().getSelectedIdentificationFiles().contains(
                            currentFile.getPath())) {
                        ((DefaultTableModel) selectedIdentificationFilesJTable.getModel()).addRow(
                                new Object[]{
                            new Integer(selectedIdentificationFilesJTable.getRowCount() + 1),
                            currentFile.getName(),
                            new Boolean(true)
                        });

                        prideConverter.getProperties().getSelectedIdentificationFiles().add(currentFile.getPath());
                    } else {
                        JOptionPane.showMessageDialog(this,
                                "A file with the name " + currentFile.getPath() +
                                " is already selected.\nThe same file can not be added twice.",
                                "File Already Selected", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }

        if (selectedIdentificationFilesJTable.getRowCount() > 0 &&
                selectedSpectraFilesJTable.getRowCount() > 0) {
            nextJButton.setEnabled(true);
        }

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
}//GEN-LAST:event_selectIdentificationsFileOrFolderJButtonActionPerformed

    /**
     * Removes the selected identification files from the table.
     * 
     * @param evt
     */
    private void deleteIdentificationsJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteIdentificationsJMenuItemActionPerformed
        if (selectedIdentificationFilesJTable.getSelectedRow() != -1) {

            prideConverter.getProperties().setSpectrumTableModel(null);

            int[] selectedRows = selectedIdentificationFilesJTable.getSelectedRows();

            for (int i = selectedRows.length - 1; i >= 0; i--) {
                prideConverter.getProperties().getSelectedIdentificationFiles().remove(selectedRows[i]);
                ((DefaultTableModel) selectedIdentificationFilesJTable.getModel()).removeRow(selectedRows[i]);
            }

            fixIdentificationTableIndices();
            nextJButton.setEnabled(selectedIdentificationFilesJTable.getRowCount() > 0);
        }
}//GEN-LAST:event_deleteIdentificationsJMenuItemActionPerformed

    /**
     * See deleteSpectraJMenuItemActionPerformed
     * 
     * @param evt
     */
    private void selectedSpectraFilesJTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_selectedSpectraFilesJTableKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            deleteSpectraJMenuItemActionPerformed(null);
        }
    }//GEN-LAST:event_selectedSpectraFilesJTableKeyReleased

    /**
     * See deleteIdentificationsJMenuItemActionPerformed
     * 
     * @param evt
     */
    private void selectedIdentificationFilesJTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_selectedIdentificationFilesJTableKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            deleteIdentificationsJMenuItemActionPerformed(null);
        }
    }//GEN-LAST:event_selectedIdentificationFilesJTableKeyReleased

    /**
     * Fixes the indices in the spectra file table so that they are in 
     * accending order starting from one.
     */
    private void fixSpectraTableIndices() {
        for (int row = 0; row <
                ((DefaultTableModel) selectedSpectraFilesJTable.getModel()).getRowCount(); row++) {
            ((DefaultTableModel) selectedSpectraFilesJTable.getModel()).setValueAt(new Integer(row +
                    1), row, 0);
        }
    }

    /**
     * Fixes the indices in the identification file table so that they are in 
     * accending order starting from one.
     */
    private void fixIdentificationTableIndices() {
        for (int row = 0; row <
                ((DefaultTableModel) selectedIdentificationFilesJTable.getModel()).getRowCount(); row++) {
            ((DefaultTableModel) selectedIdentificationFilesJTable.getModel()).setValueAt(new Integer(row +
                    1), row, 0);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelJButton;
    private javax.swing.JMenuItem deleteIdentificationsJMenuItem;
    private javax.swing.JPopupMenu deleteSelectedIdentificationFilesJPopupMenu;
    private javax.swing.JPopupMenu deleteSelectedSpectraFilesJPopupMenu;
    private javax.swing.JMenuItem deleteSpectraJMenuItem;
    private javax.swing.JButton helpJButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton nextJButton;
    private javax.swing.JButton selectIdentificationsFileOrFolderJButton;
    private javax.swing.JButton selectSpectrumFileOrFolderJButton;
    private javax.swing.JTable selectedIdentificationFilesJTable;
    private javax.swing.JTable selectedSpectraFilesJTable;
    // End of variables declaration//GEN-END:variables
}
