package no.uib.prideconverter.gui;

import no.uib.prideconverter.PRIDEConverter;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import no.uib.prideconverter.util.ExcelAdapter;

/**
 * This dialog provides the user with three different alternatives for handeling 
 * the protein isoforms: (i) always select the first one, (ii) manual selection, 
 * or (iii) by providing a list of peptide to protein matches.
 *
 * @author  Harald Barsnes
 * 
 * Created June 2008
 */
public class ProteinIsoforms extends javax.swing.JDialog {

    private ProgressDialog progressDialog;
    private PRIDEConverter prideConverter;
    private OutputDetails outputDetails;
    private ExcelAdapter excelAdapter;

    /**
     * Opens a new ProteinIsoforms dialog.
     * 
     * @param parent
     * @param modal
     * @param progressDialog
     */
    public ProteinIsoforms(java.awt.Frame parent, boolean modal, ProgressDialog progressDialog) {
        super(parent, modal);
        initComponents();

        outputDetails = (OutputDetails) parent;
        this.progressDialog = progressDialog;
        this.prideConverter = outputDetails.getPRIDEConverterReference();

        excelAdapter = new ExcelAdapter(peptideToProteinJTable);

        peptideToProteinJTable.getTableHeader().setReorderingAllowed(false);
        peptideToProteinJTable.setAutoCreateRowSorter(true);

        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().
                getResource("/no/uib/prideconverter/icons/prideConverter_16.GIF")));

        setLocationRelativeTo(outputDetails);
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        tableJPopupMenu = new javax.swing.JPopupMenu();
        pasteJMenuItem = new javax.swing.JMenuItem();
        deleteJMenuItem = new javax.swing.JMenuItem();
        addRowJMenuItem = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        manualSelectionJRadioButton = new javax.swing.JRadioButton();
        selectFirstJRadioButton = new javax.swing.JRadioButton();
        provideListJRadioButton = new javax.swing.JRadioButton();
        peptideToProteinJLabel = new javax.swing.JLabel();
        peptideToProteinJScrollPane = new javax.swing.JScrollPane();
        peptideToProteinJTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        cancelJButton = new javax.swing.JButton();
        okJButton = new javax.swing.JButton();
        aboutJButton = new javax.swing.JButton();
        helpJButton = new javax.swing.JButton();

        pasteJMenuItem.setText("Paste (Replaces the Current Content)");
        pasteJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasteJMenuItemActionPerformed(evt);
            }
        });
        tableJPopupMenu.add(pasteJMenuItem);

        deleteJMenuItem.setText("Delete Selected Rows");
        deleteJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteJMenuItemActionPerformed(evt);
            }
        });
        tableJPopupMenu.add(deleteJMenuItem);

        addRowJMenuItem.setText("Add Empty Row");
        addRowJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRowJMenuItemActionPerformed(evt);
            }
        });
        tableJPopupMenu.add(addRowJMenuItem);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Protein Isoforms Detected");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Protein Isoforms", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel1.setText("How do you want to handle protein isoforms?");

        buttonGroup.add(manualSelectionJRadioButton);
        manualSelectionJRadioButton.setText("Manual Selection");
        manualSelectionJRadioButton.setIconTextGap(20);
        manualSelectionJRadioButton.setPreferredSize(new java.awt.Dimension(13, 13));
        manualSelectionJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualSelectionJRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup.add(selectFirstJRadioButton);
        selectFirstJRadioButton.setText("Always Select The First Isoform");
        selectFirstJRadioButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        selectFirstJRadioButton.setIconTextGap(20);
        selectFirstJRadioButton.setPreferredSize(new java.awt.Dimension(13, 13));
        selectFirstJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFirstJRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup.add(provideListJRadioButton);
        provideListJRadioButton.setText("Provide a List of Peptide to Protein Matches");
        provideListJRadioButton.setIconTextGap(20);
        provideListJRadioButton.setPreferredSize(new java.awt.Dimension(13, 13));
        provideListJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provideListJRadioButtonActionPerformed(evt);
            }
        });

        peptideToProteinJLabel.setText("Peptide to Protein Matches:");

        peptideToProteinJScrollPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peptideToProteinJScrollPaneMouseClicked(evt);
            }
        });

        peptideToProteinJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Peptide Sequence", "Protein Accession"
            }
        ));
        peptideToProteinJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peptideToProteinJTableMouseClicked(evt);
            }
        });
        peptideToProteinJScrollPane.setViewportView(peptideToProteinJTable);

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel5.setText("Right click on the table and select Paste to insert data.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manualSelectionJRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectFirstJRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(provideListJRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(peptideToProteinJLabel)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(peptideToProteinJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(selectFirstJRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manualSelectionJRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(provideListJRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(peptideToProteinJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(peptideToProteinJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        cancelJButton.setText("Cancel");
        cancelJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelJButtonActionPerformed(evt);
            }
        });

        okJButton.setText("OK");
        okJButton.setEnabled(false);
        okJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okJButtonActionPerformed(evt);
            }
        });

        aboutJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/no/uib/prideconverter/icons/prideConverter_16.GIF"))); // NOI18N
        aboutJButton.setToolTipText("About");
        aboutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutJButtonActionPerformed(evt);
            }
        });

        helpJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/no/uib/prideconverter/icons/help.GIF"))); // NOI18N
        helpJButton.setToolTipText("Help");
        helpJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(helpJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aboutJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                        .addComponent(okJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cancelJButton)
                        .addComponent(okJButton))
                    .addComponent(helpJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aboutJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * See cancelJButtonActionPerformed
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cancelJButtonActionPerformed(null);
    }//GEN-LAST:event_formWindowClosing

    /**
     * Closes the dialog and cancels the conversion.
     * 
     * @param evt
     */
    private void cancelJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelJButtonActionPerformed
        prideConverter.setCancelConversion(true);
        progressDialog.setVisible(false);
        progressDialog.dispose();
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_cancelJButtonActionPerformed

    /**
     * Sends the selected choice to the main class (PRIDEConverter) and closes 
     * the dialog.
     * 
     * @param evt
     */
    private void okJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okJButtonActionPerformed

        if (selectFirstJRadioButton.isSelected()) {
            prideConverter.getProperties().setProteinIsoformSelectionType(
                    prideConverter.getProperties().PROTEIN_ISOFORMS_ALWAYS_SELECT_FIRST);
        } else if (manualSelectionJRadioButton.isSelected()) {
            prideConverter.getProperties().setProteinIsoformSelectionType(
                    prideConverter.getProperties().PROTEIN_ISOFORMS_MAUNAL_SELECTION);
        } else {
            prideConverter.getProperties().setProteinIsoformSelectionType(
                    prideConverter.getProperties().PROTEIN_ISOFORMS_PROVIDE_LIST);

            prideConverter.getProperties().setSelectedIsoformAccessions(new ArrayList());
            prideConverter.getProperties().setSelectedIsoformPeptideSequences(new ArrayList());

            for (int i = 0; i < peptideToProteinJTable.getRowCount(); i++) {
                prideConverter.getProperties().getSelectedIsoformPeptideSequences().add(
                        peptideToProteinJTable.getValueAt(i, 0));
                prideConverter.getProperties().getSelectedIsoformAccessions().add(
                        peptideToProteinJTable.getValueAt(i, 1));
            }
        }

        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_okJButtonActionPerformed

    /**
     * Enables or disables the OK button when the "provide list" option is 
     * used, based on if a list has been provided or not.
     * 
     * @param evt
     */
    private void provideListJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provideListJRadioButtonActionPerformed
        if (provideListJRadioButton.isSelected()) {
            if (peptideToProteinJTable.getRowCount() > 0) {
                okJButton.setEnabled(true);
            } else {
                okJButton.setEnabled(false);
            }
        } else {
            if (selectFirstJRadioButton.isSelected() ||
                    manualSelectionJRadioButton.isSelected()) {
                okJButton.setEnabled(true);
            } else {
                okJButton.setEnabled(false);
            }
        }
    }//GEN-LAST:event_provideListJRadioButtonActionPerformed

    /**
     * See provideListJRadioButtonActionPerformed
     */
    private void selectFirstJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFirstJRadioButtonActionPerformed
        provideListJRadioButtonActionPerformed(null);
    }//GEN-LAST:event_selectFirstJRadioButtonActionPerformed

    /**
     * See provideListJRadioButtonActionPerformed
     */
    private void manualSelectionJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualSelectionJRadioButtonActionPerformed
        provideListJRadioButtonActionPerformed(null);
    }//GEN-LAST:event_manualSelectionJRadioButtonActionPerformed

    /**
     * Opens a popup menu that lets the user paste peptide to protein matches 
     * into the table.
     * 
     * @param evt
     */
    private void peptideToProteinJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peptideToProteinJTableMouseClicked
        if (evt.getButton() == 3) {
            tableJPopupMenu.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_peptideToProteinJTableMouseClicked

    /**
     * Pastes the list of peptide to protein matches into the table.
     * 
     * @param evt
     */
    private void pasteJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasteJMenuItemActionPerformed
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        excelAdapter.actionPerformed(new java.awt.event.ActionEvent(this, 0, "Paste"));
        provideListJRadioButtonActionPerformed(null);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_pasteJMenuItemActionPerformed

    /**
     * Opens a popup menu that lets the user paste peptide to protein matches 
     * into the table.
     * 
     * @param evt
     */
    private void peptideToProteinJScrollPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peptideToProteinJScrollPaneMouseClicked
        if (evt.getButton() == 3) {
            tableJPopupMenu.show(evt.getComponent(), evt.getX(), evt.getY());
        }
}//GEN-LAST:event_peptideToProteinJScrollPaneMouseClicked

    /**
     * Opens an About PRIDE Converter dialog.
     * 
     * @param evt
     */
    private void aboutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutJButtonActionPerformed
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        new HelpWindow(this, getClass().getResource("/no/uib/prideconverter/helpfiles/AboutPRIDE_Converter.html"));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_aboutJButtonActionPerformed

    /**
     * Opens a Help dialog.
     * 
     * @param evt
     */
    private void helpJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpJButtonActionPerformed
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        new HelpWindow(this, getClass().getResource("/no/uib/prideconverter/helpfiles/ProteinIsoforms.html"));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_helpJButtonActionPerformed

    /**
     * Deletes the selected rows from the peptide to protein table.
     *
     * @param evt
     */
    private void deleteJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteJMenuItemActionPerformed
        int[] selectedRows = peptideToProteinJTable.getSelectedRows();

        for (int i = selectedRows.length - 1; i >= 0; i--) {
            ((DefaultTableModel) peptideToProteinJTable.getModel()).removeRow(selectedRows[i]);
        }

        if (provideListJRadioButton.isSelected()) {
            okJButton.setEnabled(peptideToProteinJTable.getRowCount() > 0);
        }
    }//GEN-LAST:event_deleteJMenuItemActionPerformed

    /**
     * Adds an empty row to the peptide to protein table.
     *
     * @param evt
     */
    private void addRowJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRowJMenuItemActionPerformed

        if (peptideToProteinJTable.getSelectedRow() != -1) {
            ((DefaultTableModel) peptideToProteinJTable.getModel()).insertRow(
                    peptideToProteinJTable.getSelectedRow() + 1, new Object[]{"", ""});

            peptideToProteinJTable.scrollRectToVisible(peptideToProteinJTable.getCellRect(
                peptideToProteinJTable.getSelectedRow() + 1, 0, false));

        } else {
            ((DefaultTableModel) peptideToProteinJTable.getModel()).addRow(new Object[]{"", ""});

            peptideToProteinJTable.scrollRectToVisible(peptideToProteinJTable.getCellRect(
                peptideToProteinJTable.getRowCount() - 1, 0, false));
        }
        
    }//GEN-LAST:event_addRowJMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutJButton;
    private javax.swing.JMenuItem addRowJMenuItem;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton cancelJButton;
    private javax.swing.JMenuItem deleteJMenuItem;
    private javax.swing.JButton helpJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton manualSelectionJRadioButton;
    private javax.swing.JButton okJButton;
    private javax.swing.JMenuItem pasteJMenuItem;
    private javax.swing.JLabel peptideToProteinJLabel;
    private javax.swing.JScrollPane peptideToProteinJScrollPane;
    private javax.swing.JTable peptideToProteinJTable;
    private javax.swing.JRadioButton provideListJRadioButton;
    private javax.swing.JRadioButton selectFirstJRadioButton;
    private javax.swing.JPopupMenu tableJPopupMenu;
    // End of variables declaration//GEN-END:variables
}
